<a href="https://colab.research.google.com/github/siddhantjain07/Tensorflow-Practice/blob/master/BasicOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Basic Operations using TensorFlow

###Author : Siddhant Jain
###Project : https://github.com/siddhantjain07/Tensorflow-Practice

In [0]:
from __future__ import print_function
import tensorflow as tf
import numpy

In [0]:
#Define Tensor constants
a = tf.constant(54)
b = tf.constant(63)
c = tf.constant(12)
d = tf.constant(93)

In [0]:
#Create basic math functions on created constants 
add = tf.add(a,b,name="add")
sub = tf.subtract(c,d,name="sub")
mul = tf.multiply(b,d,name="mul")
div = tf.divide(a,c,name="div")

In [9]:
#Access Tensor values
#Display them , and use .numpy() to access the value 
#Also used f-strings for printing 
print("Addition of {} and {} is {}".format(a,b,add.numpy()))
print("Subtraction of {} and {} is {}".format(c,d,sub.numpy()))
print("Multiplication for {} and {} is {}".format(b,d,mul.numpy()))
print("Divsion of {} and {} is {}".format(a,c,div.numpy()))

Addition of 54 and 63 is 117
Subtraction of 12 and 93 is -81
Multiplication for 63 and 93 is 5859
Divsion of 54 and 12 is 4.5


In [12]:
#Some more operations 
mean = tf.reduce_mean([a,b,c,d])
sum = tf.reduce_sum([a,b,c,d])

#Access Tensor Values
print("Mean of created constants",mean.numpy())
print("Sum of created constants",sum.numpy())

Mean of created constants 55
Sum of created constants 222


In [0]:
#Creating Matrices
A = tf.constant([[1.0 ,3.0],[9.0 ,7.0]])
B = tf.constant([[4.0 ,8.0],[1.0, 0.5]])

product = tf.matmul(A,B)

In [14]:
#Accessing the Tensor
product

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 7. ,  9.5],
       [43. , 75.5]], dtype=float32)>

In [15]:
#Converting Tensor to Numpy
product.numpy()

array([[ 7. ,  9.5],
       [43. , 75.5]], dtype=float32)